# Generated by Django 3.1.1 on 2020-09-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='テーマ')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_date', models.DateTimeField(null=True, verbose_name='公開日')),
                ('tag', models.CharField(blank=True, choices=[('new', '新着')], max_length=10, null=True, verbose_name='タッグ')),
            ],
        ),
    ]
