# Generated by Django 3.1.2 on 2020-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitinfo',
            name='url',
        ),
        migrations.AlterField(
            model_name='recruitinfo',
            name='tag',
            field=models.CharField(blank=True, choices=[('New', '新着')], max_length=10, null=True, verbose_name='タッグ'),
        ),
    ]
