# Generated by Django 3.1.1 on 2020-09-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=25)),
                ('publish_date', models.DateField(null=True)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('condition', models.CharField(choices=[('good', '良い'), ('normal', '普通'), ('bad', '悪い')], default='normal', max_length=10, verbose_name='体調')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='体温')),
                ('am', models.CharField(choices=[('book', 'テキスト学習'), ('project', '課題'), ('talk', '面談'), ('job-hunting', '就職活動'), ('intern', '実習'), ('training', '作業訓練'), ('absent', '該当なし'), ('others', 'その他')], max_length=20, verbose_name='午前')),
                ('am_detail', models.CharField(blank=True, max_length=100, verbose_name='午前具体内容')),
                ('pm', models.CharField(choices=[('book', 'テキスト学習'), ('project', '課題'), ('talk', '面談'), ('job-hunting', '就職活動'), ('intern', '実習'), ('training', '作業訓練'), ('absent', '該当なし'), ('others', 'その他')], max_length=20, verbose_name='午後')),
                ('pm_detail', models.CharField(blank=True, max_length=100, verbose_name='午後具体内容')),
                ('comment', models.CharField(max_length=150, verbose_name='感想や相談事など')),
            ],
        ),
        migrations.CreateModel(
            name='SaturdaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='内容')),
                ('date', models.CharField(max_length=20, verbose_name='日付')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('date', models.CharField(max_length=20, verbose_name='日付')),
                ('content', models.CharField(max_length=10, verbose_name='内容')),
                ('duration', models.CharField(max_length=20, verbose_name='時間')),
            ],
        ),
    ]
