# Generated by Django 3.1.1 on 2020-09-21 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_report_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
