# Generated by Django 3.1.1 on 2020-10-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201002_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitinfo',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='画像'),
        ),
    ]
