# Generated by Django 3.1.1 on 2020-09-20 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_recruitinfo_report_saturdayschedule_staffschedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 2, 18, 8, 48427, tzinfo=utc), null=True, verbose_name='公開日'),
        ),
    ]
