# Generated by Django 3.1.1 on 2020-09-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200922_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('can_view_all_reports', 'can view all reports'), ('can_add_report', 'can add report')]},
        ),
    ]
