# Generated by Django 3.1.1 on 2020-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_report_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='condition',
            field=models.CharField(choices=[('良い', '良い'), ('普通', '普通'), ('悪い', '悪い')], default='普通', max_length=10, verbose_name='体調'),
        ),
        migrations.AlterField(
            model_name='report',
            name='temperature',
            field=models.DecimalField(decimal_places=1, help_text='小数第一位まで\u3000例: 36.5', max_digits=3, verbose_name='体温'),
        ),
    ]
