# Generated by Django 3.1.1 on 2020-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200930_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitinfo',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
