# Generated by Django 3.1.1 on 2020-09-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200922_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=36.0, max_digits=3, verbose_name='体温'),
        ),
    ]
