# Generated by Django 3.1.1 on 2020-09-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200922_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_add_post', 'can add post')]},
        ),
        migrations.AlterModelOptions(
            name='recruitinfo',
            options={'permissions': [('can_add_recruit_info', 'can add recruit info')]},
        ),
        migrations.AlterModelOptions(
            name='saturdayschedule',
            options={'permissions': [('can_add_saturday_schedule', 'can add saturday schedule')]},
        ),
        migrations.AlterModelOptions(
            name='staffschedule',
            options={'permissions': [('can_add_staff_schedule', 'can add staff schedule')]},
        ),
    ]
