# Generated by Django 3.1.1 on 2020-09-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200920_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='公開日'),
        ),
    ]
