# Generated by Django 3.1.1 on 2020-09-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200920_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, choices=[('新着', 'New')], max_length=10, null=True, verbose_name='タッグ'),
        ),
    ]
