# Generated by Django 3.1.1 on 2020-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200920_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, choices=[('New', '新着')], max_length=10, null=True, verbose_name='タッグ'),
        ),
    ]
