# Generated by Django 3.1.1 on 2020-09-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200920_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitinfo',
            name='number',
            field=models.CharField(max_length=25, verbose_name='求人番号'),
        ),
        migrations.AlterField(
            model_name='recruitinfo',
            name='publish_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='公開日'),
        ),
        migrations.AlterField(
            model_name='recruitinfo',
            name='tag',
            field=models.CharField(blank=True, choices=[('New', '新着')], max_length=10, null=True, verbose_name='タッグ'),
        ),
        migrations.AlterField(
            model_name='recruitinfo',
            name='title',
            field=models.CharField(max_length=25, verbose_name='タイトル'),
        ),
    ]
