# Generated by Django 3.1.1 on 2020-09-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200920_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitinfo',
            name='title',
            field=models.CharField(max_length=70, verbose_name='タイトル'),
        ),
    ]
