# Generated by Django 3.1.1 on 2020-09-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200920_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitinfo',
            name='publish_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='公開日'),
        ),
    ]
