# Generated by Django 3.1.1 on 2020-09-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200920_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='日付'),
        ),
    ]
